[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/ID_SHEET_EDIT#gid=0"
# worksheet optional â€” jika kamu tidak menulis worksheet, GSheetsConnection
# biasanya akan memilih sheet pertama
