[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/10BWsokGUujHcq8mPz3NHx1Tl9L-obgvcuVnmx75UwGw/edit?gid=0#gid=0"
# worksheet optional â€” jika kamu tidak menulis worksheet, GSheetsConnection
# biasanya akan memilih sheet pertama
